#:schema node_modules/wrangler/config-schema.json
name = "hono-app"
main = "src/index.ts"
compatibility_date = "2024-12-05"

[[d1_databases]]
binding = "DB"
database_name = "hono-app"
database_id = "933a175c-6353-47f4-bbdd-0131efa3e689"
